### ISSUE TITLE
Could not run MapGenerator

### ISSUE THREAD

**Issue by bkhnk48** [ignc-research/arena-tools#4]
I have install Arena-tools, but as I run either arena-tools.py or MapGenerator.py, I get the error:
```
python MapGenerator.py
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/ukr/ros2_ws/src/arena-tools/MapGenerator.py", line 794, in <module>
    widget = MapGenerator()
  File "/home/ukr/ros2_ws/src/arena-tools/MapGenerator.py", line 38, in __init__
    self.setup_ui()
  File "/home/ukr/ros2_ws/src/arena-tools/MapGenerator.py", line 274, in setup_ui
    sim_setup_path = get_simulation_setup_pkg_prefix("")
  File "/home/ukr/ros2_ws/src/arena-tools/HelperFunctions.py", line 109, in get_simulation_setup_pkg_prefix
    rospkg.RosPack().get_path(Constants.SIMULATION_SETUP_PACKAGE), path
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 207, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: arena-simulation-setup
```

My OS is Ubuntu 22.04 and my Ros2 is Humble, my Python is 3.10.12
By the way, in Humble, I could not run `roscd arena-tools`, so I type only `python3 arena-tools.py`

**Comment by bkhnk48** [comment]
Sorry, my bad
I pull the source code from https://github.com/Arena-Rosnav/arena-tools not this https://github.com/ignc-research/arena-tools/
I close this issue right now
